# Generated by Django 3.1.1 on 2020-09-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='img',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='artistPic'),
        ),
    ]
