# Generated by Django 3.1.1 on 2020-09-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0003_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
