# Generated by Django 3.1.1 on 2020-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0005_konkanisongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konkanisongs',
            name='album',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='konkanisongs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
